//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/Controller Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControllerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControllerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controller Input"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""f7a303d3-bcf2-4de9-ac9d-bfa5e2b2ab53"",
            ""actions"": [
                {
                    ""name"": ""Left stick down"",
                    ""type"": ""Button"",
                    ""id"": ""a9a37bf5-bf98-432b-bb71-b1cbfdbc1231"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left strick right"",
                    ""type"": ""Button"",
                    ""id"": ""001557b7-5354-48d4-983e-da0ea3fc7537"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left stick up"",
                    ""type"": ""Button"",
                    ""id"": ""ff7f4d55-0533-4061-a345-5971f3ae8257"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left stick left"",
                    ""type"": ""Button"",
                    ""id"": ""276e600c-e63e-454f-b8da-8cce69fbb68c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left stick press"",
                    ""type"": ""Button"",
                    ""id"": ""80522d0e-ce65-4362-abd1-b5b044cc8cef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left trigger"",
                    ""type"": ""Button"",
                    ""id"": ""b0708e8d-e697-48a5-a099-4ad7b798533f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left shoulder"",
                    ""type"": ""Button"",
                    ""id"": ""c1dff633-aff0-4604-be5c-4a6945f08ffe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D pad left"",
                    ""type"": ""Button"",
                    ""id"": ""1f947d45-4955-4934-ab70-d74d853d1534"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D pad up"",
                    ""type"": ""Button"",
                    ""id"": ""b78fa1dd-1e86-44dc-8361-1d22c1a8dfd1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D pad right"",
                    ""type"": ""Button"",
                    ""id"": ""3fcc2da3-0fce-42ff-98fe-2b7e1d691ce1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D pad down"",
                    ""type"": ""Button"",
                    ""id"": ""5ec6106b-8634-4829-8d4e-d2991147ad9e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button west"",
                    ""type"": ""Button"",
                    ""id"": ""71ba3c24-16de-45f0-8f2c-72e285d809e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button south"",
                    ""type"": ""Button"",
                    ""id"": ""989abfbd-beea-42d9-8f3c-a635f17ba590"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button east"",
                    ""type"": ""Button"",
                    ""id"": ""7b3bf110-b683-478e-bdc3-355402401ba8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button north"",
                    ""type"": ""Button"",
                    ""id"": ""f179231f-4460-4148-9d72-ce81d526ba2b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right stick down"",
                    ""type"": ""Button"",
                    ""id"": ""50635859-64e5-4a99-a7cc-395cb6bb1021"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right stick left"",
                    ""type"": ""Button"",
                    ""id"": ""5da4629e-d0ca-4400-bf18-afbeb7f323ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right stick up"",
                    ""type"": ""Button"",
                    ""id"": ""c8d0df6d-22da-45a5-b63d-5868b816a2ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right stick right"",
                    ""type"": ""Button"",
                    ""id"": ""7ccc6960-6bf9-43de-9565-bf0cae3966b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right stick press"",
                    ""type"": ""Button"",
                    ""id"": ""f0427946-643e-4348-8833-39d34fbf6e2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right trigger"",
                    ""type"": ""Button"",
                    ""id"": ""cefb105e-4bac-4af6-9a1e-14dead49116d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right shoulder"",
                    ""type"": ""Button"",
                    ""id"": ""53e1830e-d26e-4c52-95c1-445b66366691"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start menu"",
                    ""type"": ""Button"",
                    ""id"": ""80ad3011-6e8f-4c78-ba72-9cbe42ec79f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""80fcffc9-ad7c-477f-9de5-dde33a8265e2"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left stick down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccc6f1eb-64d5-4f93-94f9-d302b26aa790"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left strick right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76ea9d0a-5c8f-4fd4-8e13-79bd256631d2"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left stick up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3331edf-6db3-4f7f-ac64-46997336063f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D pad left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d808c38-4367-4d19-b818-17c3d9fa6bc0"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D pad right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16851656-45c3-4291-baff-b4de5ae27ca3"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D pad down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30a5fc50-e87d-4e0d-9f02-471fe9297bd9"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D pad up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30e1c38c-83ac-432d-8bcf-319f37ef9dc1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button west"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4c04f2c-0bce-4bd6-a935-421fdae33092"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button south"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""626c5105-3665-47af-86d5-07822987a708"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button east"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bb2de94-b047-479e-b72e-bfa7bda7ce24"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button north"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccef3a27-aeda-49cf-a1e0-5c0aea7333d4"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right stick down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe410d35-a977-4fde-844a-4a141f984e32"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right stick left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13c0eb91-6ccd-4173-9200-33fcef9db165"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right stick up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ca15aa4-dc50-4008-b865-ecfd598c7550"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right stick right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0679afce-3435-4697-bd10-f096de50a45f"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right stick press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f29a248b-c1f6-44a4-83ca-afa6ebedc623"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left stick press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8f2ee57-a2f4-4dd4-8c96-9e2db6ddc167"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3eb1b001-5c26-4627-839e-2a0fa7a9c7fc"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left shoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcf9b43c-8a12-4858-9fb6-de235ea43875"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left stick left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37deacb2-c27c-47e9-81e0-bcd4ebe0b25f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e3dbd4e-84db-4b59-b6d8-a28a1647036f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right shoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6246a7d-e8c1-4984-9491-eb3b2a47702b"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Leftstickdown = m_Gameplay.FindAction("Left stick down", throwIfNotFound: true);
        m_Gameplay_Leftstrickright = m_Gameplay.FindAction("Left strick right", throwIfNotFound: true);
        m_Gameplay_Leftstickup = m_Gameplay.FindAction("Left stick up", throwIfNotFound: true);
        m_Gameplay_Leftstickleft = m_Gameplay.FindAction("Left stick left", throwIfNotFound: true);
        m_Gameplay_Leftstickpress = m_Gameplay.FindAction("Left stick press", throwIfNotFound: true);
        m_Gameplay_Lefttrigger = m_Gameplay.FindAction("Left trigger", throwIfNotFound: true);
        m_Gameplay_Leftshoulder = m_Gameplay.FindAction("Left shoulder", throwIfNotFound: true);
        m_Gameplay_Dpadleft = m_Gameplay.FindAction("D pad left", throwIfNotFound: true);
        m_Gameplay_Dpadup = m_Gameplay.FindAction("D pad up", throwIfNotFound: true);
        m_Gameplay_Dpadright = m_Gameplay.FindAction("D pad right", throwIfNotFound: true);
        m_Gameplay_Dpaddown = m_Gameplay.FindAction("D pad down", throwIfNotFound: true);
        m_Gameplay_Buttonwest = m_Gameplay.FindAction("Button west", throwIfNotFound: true);
        m_Gameplay_Buttonsouth = m_Gameplay.FindAction("Button south", throwIfNotFound: true);
        m_Gameplay_Buttoneast = m_Gameplay.FindAction("Button east", throwIfNotFound: true);
        m_Gameplay_Buttonnorth = m_Gameplay.FindAction("Button north", throwIfNotFound: true);
        m_Gameplay_Rightstickdown = m_Gameplay.FindAction("Right stick down", throwIfNotFound: true);
        m_Gameplay_Rightstickleft = m_Gameplay.FindAction("Right stick left", throwIfNotFound: true);
        m_Gameplay_Rightstickup = m_Gameplay.FindAction("Right stick up", throwIfNotFound: true);
        m_Gameplay_Rightstickright = m_Gameplay.FindAction("Right stick right", throwIfNotFound: true);
        m_Gameplay_Rightstickpress = m_Gameplay.FindAction("Right stick press", throwIfNotFound: true);
        m_Gameplay_Righttrigger = m_Gameplay.FindAction("Right trigger", throwIfNotFound: true);
        m_Gameplay_Rightshoulder = m_Gameplay.FindAction("Right shoulder", throwIfNotFound: true);
        m_Gameplay_Startmenu = m_Gameplay.FindAction("Start menu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Leftstickdown;
    private readonly InputAction m_Gameplay_Leftstrickright;
    private readonly InputAction m_Gameplay_Leftstickup;
    private readonly InputAction m_Gameplay_Leftstickleft;
    private readonly InputAction m_Gameplay_Leftstickpress;
    private readonly InputAction m_Gameplay_Lefttrigger;
    private readonly InputAction m_Gameplay_Leftshoulder;
    private readonly InputAction m_Gameplay_Dpadleft;
    private readonly InputAction m_Gameplay_Dpadup;
    private readonly InputAction m_Gameplay_Dpadright;
    private readonly InputAction m_Gameplay_Dpaddown;
    private readonly InputAction m_Gameplay_Buttonwest;
    private readonly InputAction m_Gameplay_Buttonsouth;
    private readonly InputAction m_Gameplay_Buttoneast;
    private readonly InputAction m_Gameplay_Buttonnorth;
    private readonly InputAction m_Gameplay_Rightstickdown;
    private readonly InputAction m_Gameplay_Rightstickleft;
    private readonly InputAction m_Gameplay_Rightstickup;
    private readonly InputAction m_Gameplay_Rightstickright;
    private readonly InputAction m_Gameplay_Rightstickpress;
    private readonly InputAction m_Gameplay_Righttrigger;
    private readonly InputAction m_Gameplay_Rightshoulder;
    private readonly InputAction m_Gameplay_Startmenu;
    public struct GameplayActions
    {
        private @ControllerInput m_Wrapper;
        public GameplayActions(@ControllerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Leftstickdown => m_Wrapper.m_Gameplay_Leftstickdown;
        public InputAction @Leftstrickright => m_Wrapper.m_Gameplay_Leftstrickright;
        public InputAction @Leftstickup => m_Wrapper.m_Gameplay_Leftstickup;
        public InputAction @Leftstickleft => m_Wrapper.m_Gameplay_Leftstickleft;
        public InputAction @Leftstickpress => m_Wrapper.m_Gameplay_Leftstickpress;
        public InputAction @Lefttrigger => m_Wrapper.m_Gameplay_Lefttrigger;
        public InputAction @Leftshoulder => m_Wrapper.m_Gameplay_Leftshoulder;
        public InputAction @Dpadleft => m_Wrapper.m_Gameplay_Dpadleft;
        public InputAction @Dpadup => m_Wrapper.m_Gameplay_Dpadup;
        public InputAction @Dpadright => m_Wrapper.m_Gameplay_Dpadright;
        public InputAction @Dpaddown => m_Wrapper.m_Gameplay_Dpaddown;
        public InputAction @Buttonwest => m_Wrapper.m_Gameplay_Buttonwest;
        public InputAction @Buttonsouth => m_Wrapper.m_Gameplay_Buttonsouth;
        public InputAction @Buttoneast => m_Wrapper.m_Gameplay_Buttoneast;
        public InputAction @Buttonnorth => m_Wrapper.m_Gameplay_Buttonnorth;
        public InputAction @Rightstickdown => m_Wrapper.m_Gameplay_Rightstickdown;
        public InputAction @Rightstickleft => m_Wrapper.m_Gameplay_Rightstickleft;
        public InputAction @Rightstickup => m_Wrapper.m_Gameplay_Rightstickup;
        public InputAction @Rightstickright => m_Wrapper.m_Gameplay_Rightstickright;
        public InputAction @Rightstickpress => m_Wrapper.m_Gameplay_Rightstickpress;
        public InputAction @Righttrigger => m_Wrapper.m_Gameplay_Righttrigger;
        public InputAction @Rightshoulder => m_Wrapper.m_Gameplay_Rightshoulder;
        public InputAction @Startmenu => m_Wrapper.m_Gameplay_Startmenu;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Leftstickdown.started += instance.OnLeftstickdown;
            @Leftstickdown.performed += instance.OnLeftstickdown;
            @Leftstickdown.canceled += instance.OnLeftstickdown;
            @Leftstrickright.started += instance.OnLeftstrickright;
            @Leftstrickright.performed += instance.OnLeftstrickright;
            @Leftstrickright.canceled += instance.OnLeftstrickright;
            @Leftstickup.started += instance.OnLeftstickup;
            @Leftstickup.performed += instance.OnLeftstickup;
            @Leftstickup.canceled += instance.OnLeftstickup;
            @Leftstickleft.started += instance.OnLeftstickleft;
            @Leftstickleft.performed += instance.OnLeftstickleft;
            @Leftstickleft.canceled += instance.OnLeftstickleft;
            @Leftstickpress.started += instance.OnLeftstickpress;
            @Leftstickpress.performed += instance.OnLeftstickpress;
            @Leftstickpress.canceled += instance.OnLeftstickpress;
            @Lefttrigger.started += instance.OnLefttrigger;
            @Lefttrigger.performed += instance.OnLefttrigger;
            @Lefttrigger.canceled += instance.OnLefttrigger;
            @Leftshoulder.started += instance.OnLeftshoulder;
            @Leftshoulder.performed += instance.OnLeftshoulder;
            @Leftshoulder.canceled += instance.OnLeftshoulder;
            @Dpadleft.started += instance.OnDpadleft;
            @Dpadleft.performed += instance.OnDpadleft;
            @Dpadleft.canceled += instance.OnDpadleft;
            @Dpadup.started += instance.OnDpadup;
            @Dpadup.performed += instance.OnDpadup;
            @Dpadup.canceled += instance.OnDpadup;
            @Dpadright.started += instance.OnDpadright;
            @Dpadright.performed += instance.OnDpadright;
            @Dpadright.canceled += instance.OnDpadright;
            @Dpaddown.started += instance.OnDpaddown;
            @Dpaddown.performed += instance.OnDpaddown;
            @Dpaddown.canceled += instance.OnDpaddown;
            @Buttonwest.started += instance.OnButtonwest;
            @Buttonwest.performed += instance.OnButtonwest;
            @Buttonwest.canceled += instance.OnButtonwest;
            @Buttonsouth.started += instance.OnButtonsouth;
            @Buttonsouth.performed += instance.OnButtonsouth;
            @Buttonsouth.canceled += instance.OnButtonsouth;
            @Buttoneast.started += instance.OnButtoneast;
            @Buttoneast.performed += instance.OnButtoneast;
            @Buttoneast.canceled += instance.OnButtoneast;
            @Buttonnorth.started += instance.OnButtonnorth;
            @Buttonnorth.performed += instance.OnButtonnorth;
            @Buttonnorth.canceled += instance.OnButtonnorth;
            @Rightstickdown.started += instance.OnRightstickdown;
            @Rightstickdown.performed += instance.OnRightstickdown;
            @Rightstickdown.canceled += instance.OnRightstickdown;
            @Rightstickleft.started += instance.OnRightstickleft;
            @Rightstickleft.performed += instance.OnRightstickleft;
            @Rightstickleft.canceled += instance.OnRightstickleft;
            @Rightstickup.started += instance.OnRightstickup;
            @Rightstickup.performed += instance.OnRightstickup;
            @Rightstickup.canceled += instance.OnRightstickup;
            @Rightstickright.started += instance.OnRightstickright;
            @Rightstickright.performed += instance.OnRightstickright;
            @Rightstickright.canceled += instance.OnRightstickright;
            @Rightstickpress.started += instance.OnRightstickpress;
            @Rightstickpress.performed += instance.OnRightstickpress;
            @Rightstickpress.canceled += instance.OnRightstickpress;
            @Righttrigger.started += instance.OnRighttrigger;
            @Righttrigger.performed += instance.OnRighttrigger;
            @Righttrigger.canceled += instance.OnRighttrigger;
            @Rightshoulder.started += instance.OnRightshoulder;
            @Rightshoulder.performed += instance.OnRightshoulder;
            @Rightshoulder.canceled += instance.OnRightshoulder;
            @Startmenu.started += instance.OnStartmenu;
            @Startmenu.performed += instance.OnStartmenu;
            @Startmenu.canceled += instance.OnStartmenu;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Leftstickdown.started -= instance.OnLeftstickdown;
            @Leftstickdown.performed -= instance.OnLeftstickdown;
            @Leftstickdown.canceled -= instance.OnLeftstickdown;
            @Leftstrickright.started -= instance.OnLeftstrickright;
            @Leftstrickright.performed -= instance.OnLeftstrickright;
            @Leftstrickright.canceled -= instance.OnLeftstrickright;
            @Leftstickup.started -= instance.OnLeftstickup;
            @Leftstickup.performed -= instance.OnLeftstickup;
            @Leftstickup.canceled -= instance.OnLeftstickup;
            @Leftstickleft.started -= instance.OnLeftstickleft;
            @Leftstickleft.performed -= instance.OnLeftstickleft;
            @Leftstickleft.canceled -= instance.OnLeftstickleft;
            @Leftstickpress.started -= instance.OnLeftstickpress;
            @Leftstickpress.performed -= instance.OnLeftstickpress;
            @Leftstickpress.canceled -= instance.OnLeftstickpress;
            @Lefttrigger.started -= instance.OnLefttrigger;
            @Lefttrigger.performed -= instance.OnLefttrigger;
            @Lefttrigger.canceled -= instance.OnLefttrigger;
            @Leftshoulder.started -= instance.OnLeftshoulder;
            @Leftshoulder.performed -= instance.OnLeftshoulder;
            @Leftshoulder.canceled -= instance.OnLeftshoulder;
            @Dpadleft.started -= instance.OnDpadleft;
            @Dpadleft.performed -= instance.OnDpadleft;
            @Dpadleft.canceled -= instance.OnDpadleft;
            @Dpadup.started -= instance.OnDpadup;
            @Dpadup.performed -= instance.OnDpadup;
            @Dpadup.canceled -= instance.OnDpadup;
            @Dpadright.started -= instance.OnDpadright;
            @Dpadright.performed -= instance.OnDpadright;
            @Dpadright.canceled -= instance.OnDpadright;
            @Dpaddown.started -= instance.OnDpaddown;
            @Dpaddown.performed -= instance.OnDpaddown;
            @Dpaddown.canceled -= instance.OnDpaddown;
            @Buttonwest.started -= instance.OnButtonwest;
            @Buttonwest.performed -= instance.OnButtonwest;
            @Buttonwest.canceled -= instance.OnButtonwest;
            @Buttonsouth.started -= instance.OnButtonsouth;
            @Buttonsouth.performed -= instance.OnButtonsouth;
            @Buttonsouth.canceled -= instance.OnButtonsouth;
            @Buttoneast.started -= instance.OnButtoneast;
            @Buttoneast.performed -= instance.OnButtoneast;
            @Buttoneast.canceled -= instance.OnButtoneast;
            @Buttonnorth.started -= instance.OnButtonnorth;
            @Buttonnorth.performed -= instance.OnButtonnorth;
            @Buttonnorth.canceled -= instance.OnButtonnorth;
            @Rightstickdown.started -= instance.OnRightstickdown;
            @Rightstickdown.performed -= instance.OnRightstickdown;
            @Rightstickdown.canceled -= instance.OnRightstickdown;
            @Rightstickleft.started -= instance.OnRightstickleft;
            @Rightstickleft.performed -= instance.OnRightstickleft;
            @Rightstickleft.canceled -= instance.OnRightstickleft;
            @Rightstickup.started -= instance.OnRightstickup;
            @Rightstickup.performed -= instance.OnRightstickup;
            @Rightstickup.canceled -= instance.OnRightstickup;
            @Rightstickright.started -= instance.OnRightstickright;
            @Rightstickright.performed -= instance.OnRightstickright;
            @Rightstickright.canceled -= instance.OnRightstickright;
            @Rightstickpress.started -= instance.OnRightstickpress;
            @Rightstickpress.performed -= instance.OnRightstickpress;
            @Rightstickpress.canceled -= instance.OnRightstickpress;
            @Righttrigger.started -= instance.OnRighttrigger;
            @Righttrigger.performed -= instance.OnRighttrigger;
            @Righttrigger.canceled -= instance.OnRighttrigger;
            @Rightshoulder.started -= instance.OnRightshoulder;
            @Rightshoulder.performed -= instance.OnRightshoulder;
            @Rightshoulder.canceled -= instance.OnRightshoulder;
            @Startmenu.started -= instance.OnStartmenu;
            @Startmenu.performed -= instance.OnStartmenu;
            @Startmenu.canceled -= instance.OnStartmenu;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnLeftstickdown(InputAction.CallbackContext context);
        void OnLeftstrickright(InputAction.CallbackContext context);
        void OnLeftstickup(InputAction.CallbackContext context);
        void OnLeftstickleft(InputAction.CallbackContext context);
        void OnLeftstickpress(InputAction.CallbackContext context);
        void OnLefttrigger(InputAction.CallbackContext context);
        void OnLeftshoulder(InputAction.CallbackContext context);
        void OnDpadleft(InputAction.CallbackContext context);
        void OnDpadup(InputAction.CallbackContext context);
        void OnDpadright(InputAction.CallbackContext context);
        void OnDpaddown(InputAction.CallbackContext context);
        void OnButtonwest(InputAction.CallbackContext context);
        void OnButtonsouth(InputAction.CallbackContext context);
        void OnButtoneast(InputAction.CallbackContext context);
        void OnButtonnorth(InputAction.CallbackContext context);
        void OnRightstickdown(InputAction.CallbackContext context);
        void OnRightstickleft(InputAction.CallbackContext context);
        void OnRightstickup(InputAction.CallbackContext context);
        void OnRightstickright(InputAction.CallbackContext context);
        void OnRightstickpress(InputAction.CallbackContext context);
        void OnRighttrigger(InputAction.CallbackContext context);
        void OnRightshoulder(InputAction.CallbackContext context);
        void OnStartmenu(InputAction.CallbackContext context);
    }
}
